import re, subprocess, time, sys, os
from playwright.sync_api import sync_playwright
log = open("/out/app.log", "w")
app = subprocess.Popen(["/out/mpc-installer", "--no-browser", "--port", "8765"], stdout=log, stderr=subprocess.STDOUT)
time.sleep(1.5)
link = re.search(r"http://127\.0\.0\.1:8765/\?t=\w+", open("/out/app.log").read()).group(0)
print("link ok")
fails = []
def check(name, cond, extra=""):
    print(("PASS " if cond else "FAIL ") + name + ((" " + str(extra)) if extra and not cond else ""))
    if not cond: fails.append(name)
try:
    with sync_playwright() as p:
        b = p.chromium.launch()
        ctx = b.new_context(bypass_csp=True, viewport={"width": 1000, "height": 1300}); pg = ctx.new_page()
        errs = []; pg.on("pageerror", lambda e: errs.append(str(e)))
        pg.goto(link)
        check("URL token is removed from the address bar", "t=" not in pg.evaluate("location.href"))
        check("steps 2 and 3 locked before connecting", "off" in pg.locator("#s2").get_attribute("class"))
        pg.screenshot(path="/out/ui-1-start.png")
        pg.fill("#host", "1.2.3.4; rm -rf /"); pg.click("#connect")
        pg.wait_for_function("document.getElementById('connmsg').textContent.length > 0")
        check("bad address refused", "numbers and dots" in pg.locator("#connmsg").text_content(), pg.locator("#connmsg").text_content())
        pg.fill("#host", "127.0.0.1"); pg.fill("#pw", "secret"); pg.click("#connect")
        pg.wait_for_function("document.getElementById('connmsg').className.indexOf('ok') >= 0 || document.getElementById('connmsg').className.indexOf('err') >= 0", timeout=30000)
        m = pg.locator("#connmsg").text_content()
        print("connect message:", m)
        check("connected to the device", "Connected to 127.0.0.1" in m and "2 plugin folders" in m, m)
        check("no problems reported", "Cannot install here" not in m, m)
        pg.wait_for_selector("#cat input[type=checkbox]", timeout=20000)
        n = pg.locator("#cat input[type=checkbox]").count(); check("catalog rows", n >= 4, n)
        check("nothing from the catalog is marked yet", pg.locator("#cat .tag.ok").count() == 0)
        pg.screenshot(path="/out/ui-2-connected.png")
        pg.check("#c_acid")
        pg.set_input_files("#file", "/out/fake-1.4.0.zip")
        pg.wait_for_selector("#ups li", timeout=20000)
        check("dropped zip listed", "Test Synth" in pg.locator("#ups").text_content())
        pg.set_input_files("#file", {"name": "junk.zip", "mimeType": "application/zip", "buffer": b"nope"})
        pg.wait_for_function("document.getElementById('upmsg').textContent.indexOf('junk.zip') >= 0")
        check("junk zip refused with a reason", "not a zip" in pg.locator("#upmsg").text_content(), pg.locator("#upmsg").text_content())
        check("summary counts both", "2 plugins selected" in pg.locator("#summary").text_content(), pg.locator("#summary").text_content())
        pg.click("#go")
        pg.wait_for_selector("#dlg[open]")
        dt = pg.locator("#dlgtxt").text_content(); print("dialog:", dt)
        check("dialog is honest about restarts", "at least once" in dt, dt)
        check("dialog asks to save the project", "Save your project first" in pg.locator("#dlg").text_content())
        pg.screenshot(path="/out/ui-3-confirm.png")
        pg.click("#no")
        check("cancel leaves the log hidden and nothing installed", pg.locator("#log").is_hidden() and not os.path.exists("/sdcard/Synths/sd88me - VST - Acid"))
        pg.click("#go"); pg.wait_for_selector("#dlg[open]"); pg.click("#yes")
        pg.wait_for_function("document.getElementById('result').className.indexOf('ok') >= 0 || document.getElementById('result').className.indexOf('err') >= 0", timeout=180000)
        res = pg.locator("#result").text_content(); logtxt = pg.locator("#log").text_content()
        print("RESULT:", res); print(logtxt)
        pg.screenshot(path="/out/ui-4-done.png")
        check("install finished OK", "Done" in res, res)
        check("log shows the download check", "checked against the catalog's sha256" in logtxt)
        check("Acid installed as one folder", os.path.exists("/sdcard/Synths/sd88me - VST - Acid/acid.so") and os.path.exists("/sdcard/Synths/sd88me - VST - Acid/plugin-meta.xml"))
        check("new-installer plugin installed", os.path.exists("/sdcard/Synths/Acme - VST - Test Synth/test_synth.so"))
        st = open("/media/az01-internal/Settings/MPC/MPC.settings").read()
        check("both entries registered in MPC.settings", st.count("<PLUGIN ") == 2 and "acid.so" in st and "test_synth.so" in st)
        calls = open("/tmp/systemctl.log").read().split("\n")
        print("systemctl calls:", [c for c in calls if c])
        check("MPC: old installer restarts by itself, then one batch stop/start", [c for c in calls if c] == ["stop acvs", "start acvs", "stop acvs", "start acvs"], calls)
        state = open("/sdcard/Synths/.mpc-store").read()
        check("what was installed is remembered", "acid\t1.0.1" in state and "test-synth\t1.4.0" in state, state)
        check("nothing left in /tmp", not [d for d in os.listdir("/tmp") if d.startswith("mpc-installer-") and os.path.isdir("/tmp/" + d) and os.path.exists("/tmp/" + d + "/p1")])
        pg.wait_for_selector("#cat .tag.ok")
        check("Acid now shows as on the device", "on the device" in pg.locator("#cat li").filter(has_text="Acid").first.text_content())

        # --- removal
        pg.wait_for_selector("#dev li input", timeout=20000)
        devtxt = pg.locator("#dev").text_content()
        check("device list shows the plugins", "Acid" in devtxt and "Test Synth" in devtxt, devtxt)
        check("an unidentified plugin cannot be ticked, and says why", pg.locator("#d_mystery\\ -\\ VST\\ -\\ Thing").is_disabled() and "can't tell which files" in devtxt)
        check("Remove is disabled until something is ticked", pg.locator("#rm").is_disabled())
        pg.check("#d_Acme\\ -\\ VST\\ -\\ Test\\ Synth")
        pg.click("#rm"); pg.wait_for_selector("#dlg[open]")
        dt = pg.locator("#dlg").text_content(); print("remove dialog:", dt.strip()[:300])
        check("remove dialog says what goes and what is kept", "Remove from your device?" in dt and "Test Synth" in dt and "MPC restarts once" in dt and "Save your project first" in dt)
        pg.screenshot(path="/out/ui-7-remove-confirm.png")
        pg.click("#no")
        check("cancel removes nothing", os.path.exists("/sdcard/Synths/Acme - VST - Test Synth/test_synth.so"))
        pg.click("#rm"); pg.wait_for_selector("#dlg[open]"); pg.click("#yes")
        pg.wait_for_function("document.getElementById('rmresult').className.indexOf('ok') >= 0 || document.getElementById('rmresult').className.indexOf('err') >= 0", timeout=120000)
        rr = pg.locator("#rmresult").text_content(); print("REMOVE RESULT:", rr); print(pg.locator("#rmlog").text_content())
        pg.screenshot(path="/out/ui-8-removed.png")
        check("removal finished OK", "Done" in rr, rr)
        check("Test Synth's folder is gone", not os.path.exists("/sdcard/Synths/Acme - VST - Test Synth"))
        st2 = open("/media/az01-internal/Settings/MPC/MPC.settings").read()
        check("its entry is gone and Acid's stays", "test_synth.so" not in st2 and "acid.so" in st2, st2)
        check("Acid untouched", os.path.exists("/sdcard/Synths/sd88me - VST - Acid/acid.so"))
        check("the unidentified plugin was not touched", os.path.exists("/sdcard/Synths/mystery - VST - Thing/plugin-meta.xml"))
        calls2 = [c for c in open("/tmp/systemctl.log").read().split("\n") if c]
        check("one more stop/start for the removal", calls2[4:] == ["stop acvs", "start acvs"], calls2)
        check("the recorded version is forgotten", "test-synth" not in open("/sdcard/Synths/.mpc-store").read())
        check("a settings backup was made", len([f for f in os.listdir("/media/az01-internal/Settings/MPC") if f.startswith("MPC.settings.bak-remove-")]) == 1)
        pg.wait_for_function("document.querySelectorAll('#dev li').length >= 2")
        check("the list refreshes", "Test Synth" not in pg.locator("#dev").text_content())
        check("no page errors", not errs, errs)
        b.close()
finally:
    app.terminate()
print("FAILED: %s" % fails if fails else "ALL PASSED")
sys.exit(1 if fails else 0)
